data_config:
  condition: "text"
  train_data_type: "numpy"
  data_folder: "toy_imagenet_cache/"
  csv_path:
  sample_stride: 1
  video_column: "video"
  class_column:
  caption_column: "caption"
  use_safer_augment: True
  image_video_joint: False
  use_image_num:
  num_parallel_workers: 8
  max_rowsize: 64
  shuffle: True
