Interpolation-1:
  sd_config: "configs/stable_diffusion/v1-inference-mmv2-interpolation.yaml"
  motion_module:
    - "models/motion_module/mm_sd_v15_v2.ckpt"
    # - "outputs/mmv2_train_webvid5/2024-01-11T22-38-19/ckpt/ad-16000.ckpt"

  seed:           43
  steps:          30
  guidance_scale: 7.5

  conditions_image_indexs: [0,-1]
  conditions_images:
    - "webvid5/1/frame_0000.png"
    - "webvid5/1/frame_0015.png"

  prompt:
    - "Disco light leaks disco ball light reflections shaped rectangular and line with motion blur effect."

  n_prompt:
    - ""

Interpolation-1:
  sd_config: "configs/stable_diffusion/v1-inference-mmv2-interpolation.yaml"
  motion_module:
    - "models/motion_module/mm_sd_v15_v2.ckpt"
    # - "outputs/mmv2_train_webvid5/2024-01-11T22-38-19/ckpt/ad-16000.ckpt"

  seed:           43
  steps:          30
  guidance_scale: 7.5

  conditions_image_indexs: [0,-1]
  conditions_images:
    - "webvid5/2/frame_0000.png"
    - "webvid5/2/frame_0015.png"

  prompt:
    - "Cloudy moscow kremlin time lapse"

  n_prompt:
    - ""
